{
    'name': 'Practice',
    'version': '1.1',
    'summary': 'For Practice',
    'sequence': 2,
    'description': 'For Practice Access Rights',
    'author': 'RP',
    'license': '',
    'depends': ['base','mail'],
    'data': ['security/ir.model.access.csv',
             'data/data.xml',
             'data/new_template.xml',
             "views/menu.xml",
             "views/practice_view.xml",
             "views/company_view.xml",
             "views/work_view.xml",
             "views/licenced_company_view.xml",
             ],
    'demo': [''],
    'application': True,
    'installable': True,
}
