{
    'name': 'Practice',
    'version': '1.1',
    'summary': 'For Practice',
    'sequence': 2,
    'description': 'For Practice Access Rights',
    'author': 'RP',
    'license': '',
    'depends': ['base', 'mail', 'web', 'hr_expense', 'purchase', 'website', 'sale','planning','point_of_sale'],
    'data': ['security/ir.model.access.csv',
             'data/data.xml',
             'data/new_template.xml',
             "views/menu.xml",
             "views/practice_view.xml",
             "views/company_view.xml",
             "views/work_view.xml",
             "views/licenced_company_view.xml",
             "views/equipment_view.xml",
             "views/equipment_order_view.xml",
             "views/equipment_delivery_view.xml",
             "views/sale_order_custom_button_connection.xml",
             "views/company_js_connection.xml",
             "views/purchase_portal_sidebar_inherite.xml",
             "views/pos_order_new_note.xml",
             "report/hr_expense_qweb_report.xml",
             ],
    'assets': {
        'web.assets_backend': [
            'Practice/static/src/components/hr_expense_custom_button_action.js',
            'Practice/static/src/components/planning_custom_button_action.js',
            'Practice/static/src/components/website_home.js',
            'Practice/static/src/controllers/sale_order_form_custom_button.js',
            'Practice/static/src/controllers/sale_order_list_custom_button.js',
            'Practice/static/src/controllers/company_custom_controller.js',
            'Practice/static/src/views/hr_expense_custom_button.xml',
            'Practice/static/src/views/website_home_inherite_try.xml',
            'Practice/static/src/views/sale_order_custom_button.xml',
            'Practice/static/src/views/company_controll_pannel_button.xml',
            'Practice/static/src/views/sale_order_custom_button_connection.xml',
        ],
        'point_of_sale._assets_pos':[
            'Practice/static/src/pos/**/*.js',
            'Practice/static/src/pos/**/*.xml',
            'Practice/static/src/pos/**/*.scss',
        ],
        'web.assets_frontend': [
            'Practice/static/src/js/purchase_portal_sidebar_inheritance.js',
        ],
    },
    'demo': [''],
    'application': True,
    'installable': True,
}
