from . import  practice
from . import company
from . import work
from . import licenced_company
from . import equipment
from . import equipment_order
from . import  equipment_delivery
from . import hr_expence
from . import pos_order
from . import  pos_discount
from . import duplicate_sale_order
from . import pos_config_location
from . import  pos_config_inherit